//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Part", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Part : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserMessageField;
        
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserMessage {
            get {
                return this.UserMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMessageField, value) != true)) {
                    this.UserMessageField = value;
                    this.RaisePropertyChanged("UserMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.MessagesCrudSoap")]
    public interface MessagesCrudSoap {
        
        // CODEGEN: Generating message contract since element name MessageListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageList", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference2.MessageListResponse MessageList(WindowsFormsApp1.ServiceReference2.MessageListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageList", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.MessageListResponse> MessageListAsync(WindowsFormsApp1.ServiceReference2.MessageListRequest request);
        
        // CODEGEN: Generating message contract since element name ConfirmedMessagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedMessages", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse ConfirmedMessages(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse> ConfirmedMessagesAsync(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddedMessage", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference2.AddedMessageResponse AddedMessage(WindowsFormsApp1.ServiceReference2.AddedMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddedMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.AddedMessageResponse> AddedMessageAsync(WindowsFormsApp1.ServiceReference2.AddedMessageRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedUser", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse ConfirmedUser(WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse> ConfirmedUserAsync(WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageList", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.MessageListRequestBody Body;
        
        public MessageListRequest() {
        }
        
        public MessageListRequest(WindowsFormsApp1.ServiceReference2.MessageListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MessageListRequestBody {
        
        public MessageListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.MessageListResponseBody Body;
        
        public MessageListResponse() {
        }
        
        public MessageListResponse(WindowsFormsApp1.ServiceReference2.MessageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference2.Part[] MessageListResult;
        
        public MessageListResponseBody() {
        }
        
        public MessageListResponseBody(WindowsFormsApp1.ServiceReference2.Part[] MessageListResult) {
            this.MessageListResult = MessageListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedMessages", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequestBody Body;
        
        public ConfirmedMessagesRequest() {
        }
        
        public ConfirmedMessagesRequest(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MessageID;
        
        public ConfirmedMessagesRequestBody() {
        }
        
        public ConfirmedMessagesRequestBody(int MessageID) {
            this.MessageID = MessageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponseBody Body;
        
        public ConfirmedMessagesResponse() {
        }
        
        public ConfirmedMessagesResponse(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConfirmedMessagesResult;
        
        public ConfirmedMessagesResponseBody() {
        }
        
        public ConfirmedMessagesResponseBody(string ConfirmedMessagesResult) {
            this.ConfirmedMessagesResult = ConfirmedMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddedMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddedMessage", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.AddedMessageRequestBody Body;
        
        public AddedMessageRequest() {
        }
        
        public AddedMessageRequest(WindowsFormsApp1.ServiceReference2.AddedMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddedMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int categoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userMessage;
        
        public AddedMessageRequestBody() {
        }
        
        public AddedMessageRequestBody(string username, int categoryID, string userMessage) {
            this.username = username;
            this.categoryID = categoryID;
            this.userMessage = userMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddedMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddedMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.AddedMessageResponseBody Body;
        
        public AddedMessageResponse() {
        }
        
        public AddedMessageResponse(WindowsFormsApp1.ServiceReference2.AddedMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddedMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddedMessageResult;
        
        public AddedMessageResponseBody() {
        }
        
        public AddedMessageResponseBody(string AddedMessageResult) {
            this.AddedMessageResult = AddedMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedUser", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.ConfirmedUserRequestBody Body;
        
        public ConfirmedUserRequest() {
        }
        
        public ConfirmedUserRequest(WindowsFormsApp1.ServiceReference2.ConfirmedUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public ConfirmedUserRequestBody() {
        }
        
        public ConfirmedUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.ConfirmedUserResponseBody Body;
        
        public ConfirmedUserResponse() {
        }
        
        public ConfirmedUserResponse(WindowsFormsApp1.ServiceReference2.ConfirmedUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConfirmedUserResult;
        
        public ConfirmedUserResponseBody() {
        }
        
        public ConfirmedUserResponseBody(string ConfirmedUserResult) {
            this.ConfirmedUserResult = ConfirmedUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagesCrudSoapChannel : WindowsFormsApp1.ServiceReference2.MessagesCrudSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagesCrudSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference2.MessagesCrudSoap>, WindowsFormsApp1.ServiceReference2.MessagesCrudSoap {
        
        public MessagesCrudSoapClient() {
        }
        
        public MessagesCrudSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagesCrudSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesCrudSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesCrudSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.MessageListResponse WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.MessageList(WindowsFormsApp1.ServiceReference2.MessageListRequest request) {
            return base.Channel.MessageList(request);
        }
        
        public WindowsFormsApp1.ServiceReference2.Part[] MessageList() {
            WindowsFormsApp1.ServiceReference2.MessageListRequest inValue = new WindowsFormsApp1.ServiceReference2.MessageListRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.MessageListRequestBody();
            WindowsFormsApp1.ServiceReference2.MessageListResponse retVal = ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).MessageList(inValue);
            return retVal.Body.MessageListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.MessageListResponse> WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.MessageListAsync(WindowsFormsApp1.ServiceReference2.MessageListRequest request) {
            return base.Channel.MessageListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.MessageListResponse> MessageListAsync() {
            WindowsFormsApp1.ServiceReference2.MessageListRequest inValue = new WindowsFormsApp1.ServiceReference2.MessageListRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.MessageListRequestBody();
            return ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).MessageListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.ConfirmedMessages(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest request) {
            return base.Channel.ConfirmedMessages(request);
        }
        
        public string ConfirmedMessages(int MessageID) {
            WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest inValue = new WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequestBody();
            inValue.Body.MessageID = MessageID;
            WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse retVal = ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).ConfirmedMessages(inValue);
            return retVal.Body.ConfirmedMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse> WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.ConfirmedMessagesAsync(WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest request) {
            return base.Channel.ConfirmedMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedMessagesResponse> ConfirmedMessagesAsync(int MessageID) {
            WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest inValue = new WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.ConfirmedMessagesRequestBody();
            inValue.Body.MessageID = MessageID;
            return ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).ConfirmedMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.AddedMessageResponse WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.AddedMessage(WindowsFormsApp1.ServiceReference2.AddedMessageRequest request) {
            return base.Channel.AddedMessage(request);
        }
        
        public string AddedMessage(string username, int categoryID, string userMessage) {
            WindowsFormsApp1.ServiceReference2.AddedMessageRequest inValue = new WindowsFormsApp1.ServiceReference2.AddedMessageRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.AddedMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.categoryID = categoryID;
            inValue.Body.userMessage = userMessage;
            WindowsFormsApp1.ServiceReference2.AddedMessageResponse retVal = ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).AddedMessage(inValue);
            return retVal.Body.AddedMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.AddedMessageResponse> WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.AddedMessageAsync(WindowsFormsApp1.ServiceReference2.AddedMessageRequest request) {
            return base.Channel.AddedMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.AddedMessageResponse> AddedMessageAsync(string username, int categoryID, string userMessage) {
            WindowsFormsApp1.ServiceReference2.AddedMessageRequest inValue = new WindowsFormsApp1.ServiceReference2.AddedMessageRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.AddedMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.categoryID = categoryID;
            inValue.Body.userMessage = userMessage;
            return ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).AddedMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.ConfirmedUser(WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest request) {
            return base.Channel.ConfirmedUser(request);
        }
        
        public string ConfirmedUser(string username) {
            WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest inValue = new WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.ConfirmedUserRequestBody();
            inValue.Body.username = username;
            WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse retVal = ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).ConfirmedUser(inValue);
            return retVal.Body.ConfirmedUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse> WindowsFormsApp1.ServiceReference2.MessagesCrudSoap.ConfirmedUserAsync(WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest request) {
            return base.Channel.ConfirmedUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.ConfirmedUserResponse> ConfirmedUserAsync(string username) {
            WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest inValue = new WindowsFormsApp1.ServiceReference2.ConfirmedUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.ConfirmedUserRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsApp1.ServiceReference2.MessagesCrudSoap)(this)).ConfirmedUserAsync(inValue);
        }
    }
}
