//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIArayuzForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usrs", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usrs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private bool StatusField;
        
        private bool AdminStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool AdminStatus {
            get {
                return this.AdminStatusField;
            }
            set {
                if ((this.AdminStatusField.Equals(value) != true)) {
                    this.AdminStatusField = value;
                    this.RaisePropertyChanged("AdminStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.LoginCrudsSoap")]
    public interface LoginCrudsSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        UIArayuzForm.ServiceReference1.LoginResponse Login(UIArayuzForm.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.LoginResponse> LoginAsync(UIArayuzForm.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        UIArayuzForm.ServiceReference1.RegisterResponse Register(UIArayuzForm.ServiceReference1.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.RegisterResponse> RegisterAsync(UIArayuzForm.ServiceReference1.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name UserShowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserShow", ReplyAction="*")]
        UIArayuzForm.ServiceReference1.UserShowResponse UserShow(UIArayuzForm.ServiceReference1.UserShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserShow", ReplyAction="*")]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.UserShowResponse> UserShowAsync(UIArayuzForm.ServiceReference1.UserShowRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedLogin", ReplyAction="*")]
        UIArayuzForm.ServiceReference1.ConfirmedLoginResponse ConfirmedLogin(UIArayuzForm.ServiceReference1.ConfirmedLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.ConfirmedLoginResponse> ConfirmedLoginAsync(UIArayuzForm.ServiceReference1.ConfirmedLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(UIArayuzForm.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(UIArayuzForm.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(UIArayuzForm.ServiceReference1.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string Name, string Surname, string Phone, string Username, string Password) {
            this.Name = Name;
            this.Surname = Surname;
            this.Phone = Phone;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(UIArayuzForm.ServiceReference1.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserShow", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.UserShowRequestBody Body;
        
        public UserShowRequest() {
        }
        
        public UserShowRequest(UIArayuzForm.ServiceReference1.UserShowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UserShowRequestBody {
        
        public UserShowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserShowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserShowResponse", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.UserShowResponseBody Body;
        
        public UserShowResponse() {
        }
        
        public UserShowResponse(UIArayuzForm.ServiceReference1.UserShowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserShowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UIArayuzForm.ServiceReference1.Usrs[] UserShowResult;
        
        public UserShowResponseBody() {
        }
        
        public UserShowResponseBody(UIArayuzForm.ServiceReference1.Usrs[] UserShowResult) {
            this.UserShowResult = UserShowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedLogin", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.ConfirmedLoginRequestBody Body;
        
        public ConfirmedLoginRequest() {
        }
        
        public ConfirmedLoginRequest(UIArayuzForm.ServiceReference1.ConfirmedLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public ConfirmedLoginRequestBody() {
        }
        
        public ConfirmedLoginRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmedLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmedLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public UIArayuzForm.ServiceReference1.ConfirmedLoginResponseBody Body;
        
        public ConfirmedLoginResponse() {
        }
        
        public ConfirmedLoginResponse(UIArayuzForm.ServiceReference1.ConfirmedLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmedLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConfirmedLoginResult;
        
        public ConfirmedLoginResponseBody() {
        }
        
        public ConfirmedLoginResponseBody(string ConfirmedLoginResult) {
            this.ConfirmedLoginResult = ConfirmedLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginCrudsSoapChannel : UIArayuzForm.ServiceReference1.LoginCrudsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCrudsSoapClient : System.ServiceModel.ClientBase<UIArayuzForm.ServiceReference1.LoginCrudsSoap>, UIArayuzForm.ServiceReference1.LoginCrudsSoap {
        
        public LoginCrudsSoapClient() {
        }
        
        public LoginCrudsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginCrudsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginCrudsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginCrudsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UIArayuzForm.ServiceReference1.LoginResponse UIArayuzForm.ServiceReference1.LoginCrudsSoap.Login(UIArayuzForm.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string UserName, string Password) {
            UIArayuzForm.ServiceReference1.LoginRequest inValue = new UIArayuzForm.ServiceReference1.LoginRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            UIArayuzForm.ServiceReference1.LoginResponse retVal = ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.LoginResponse> UIArayuzForm.ServiceReference1.LoginCrudsSoap.LoginAsync(UIArayuzForm.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.LoginResponse> LoginAsync(string UserName, string Password) {
            UIArayuzForm.ServiceReference1.LoginRequest inValue = new UIArayuzForm.ServiceReference1.LoginRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UIArayuzForm.ServiceReference1.RegisterResponse UIArayuzForm.ServiceReference1.LoginCrudsSoap.Register(UIArayuzForm.ServiceReference1.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string Name, string Surname, string Phone, string Username, string Password) {
            UIArayuzForm.ServiceReference1.RegisterRequest inValue = new UIArayuzForm.ServiceReference1.RegisterRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.RegisterRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Phone = Phone;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            UIArayuzForm.ServiceReference1.RegisterResponse retVal = ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.RegisterResponse> UIArayuzForm.ServiceReference1.LoginCrudsSoap.RegisterAsync(UIArayuzForm.ServiceReference1.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.RegisterResponse> RegisterAsync(string Name, string Surname, string Phone, string Username, string Password) {
            UIArayuzForm.ServiceReference1.RegisterRequest inValue = new UIArayuzForm.ServiceReference1.RegisterRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.RegisterRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Phone = Phone;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UIArayuzForm.ServiceReference1.UserShowResponse UIArayuzForm.ServiceReference1.LoginCrudsSoap.UserShow(UIArayuzForm.ServiceReference1.UserShowRequest request) {
            return base.Channel.UserShow(request);
        }
        
        public UIArayuzForm.ServiceReference1.Usrs[] UserShow() {
            UIArayuzForm.ServiceReference1.UserShowRequest inValue = new UIArayuzForm.ServiceReference1.UserShowRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.UserShowRequestBody();
            UIArayuzForm.ServiceReference1.UserShowResponse retVal = ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).UserShow(inValue);
            return retVal.Body.UserShowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.UserShowResponse> UIArayuzForm.ServiceReference1.LoginCrudsSoap.UserShowAsync(UIArayuzForm.ServiceReference1.UserShowRequest request) {
            return base.Channel.UserShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.UserShowResponse> UserShowAsync() {
            UIArayuzForm.ServiceReference1.UserShowRequest inValue = new UIArayuzForm.ServiceReference1.UserShowRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.UserShowRequestBody();
            return ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).UserShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UIArayuzForm.ServiceReference1.ConfirmedLoginResponse UIArayuzForm.ServiceReference1.LoginCrudsSoap.ConfirmedLogin(UIArayuzForm.ServiceReference1.ConfirmedLoginRequest request) {
            return base.Channel.ConfirmedLogin(request);
        }
        
        public string ConfirmedLogin(string username) {
            UIArayuzForm.ServiceReference1.ConfirmedLoginRequest inValue = new UIArayuzForm.ServiceReference1.ConfirmedLoginRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.ConfirmedLoginRequestBody();
            inValue.Body.username = username;
            UIArayuzForm.ServiceReference1.ConfirmedLoginResponse retVal = ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).ConfirmedLogin(inValue);
            return retVal.Body.ConfirmedLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.ConfirmedLoginResponse> UIArayuzForm.ServiceReference1.LoginCrudsSoap.ConfirmedLoginAsync(UIArayuzForm.ServiceReference1.ConfirmedLoginRequest request) {
            return base.Channel.ConfirmedLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<UIArayuzForm.ServiceReference1.ConfirmedLoginResponse> ConfirmedLoginAsync(string username) {
            UIArayuzForm.ServiceReference1.ConfirmedLoginRequest inValue = new UIArayuzForm.ServiceReference1.ConfirmedLoginRequest();
            inValue.Body = new UIArayuzForm.ServiceReference1.ConfirmedLoginRequestBody();
            inValue.Body.username = username;
            return ((UIArayuzForm.ServiceReference1.LoginCrudsSoap)(this)).ConfirmedLoginAsync(inValue);
        }
    }
}
